"""empty message

Revision ID: 333d4de9f82
Revises: 8d65c74d66
Create Date: 2016-03-24 16:49:33.260180

"""

# revision identifiers, used by Alembic.
revision = '333d4de9f82'
down_revision = '8d65c74d66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
