"""empty message

Revision ID: 3881730d29a
Revises: 3e7137110be
Create Date: 2016-03-28 10:45:24.109890

"""

# revision identifiers, used by Alembic.
revision = '3881730d29a'
down_revision = '3e7137110be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
