"""empty message

Revision ID: 3e7137110be
Revises: 333d4de9f82
Create Date: 2016-03-28 10:43:16.611024

"""

# revision identifiers, used by Alembic.
revision = '3e7137110be'
down_revision = '333d4de9f82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('play_times', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'play_times')
    ### end Alembic commands ###
